### ISSUE TITLE
download from douyin error

### ISSUE THREAD

**Issue by Green-m** [foamzou/media-get#2]
```
❯ ./media-get-0.2.4-linux -u "https://www.douyin.com/video/7008882438181031179"
-----------------
 start fetch video: https://aweme.snssdk.com/aweme/v1/playwm/?video_id=v0300fg10000c528qi3c77uccgtdfi70&ratio=720p&line=0

panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/foamzou/audio-get/utils.GetExtFromUrl(0xc0004c2070, 0x65, 0x24, 0x855ec5)
	github.com/foamzou/audio-get/utils/url.go:11 +0x175
github.com/foamzou/audio-get/processor.(*Processor).downloadVideo(0xc00019bf68, 0xc000394000, 0x8d0258, 0xc00000e080)
	github.com/foamzou/audio-get/processor/download.go:76 +0x7c5
github.com/foamzou/audio-get/processor.(*Processor).download(0xc00019bf68, 0xc000394000, 0x6, 0x0)
	github.com/foamzou/audio-get/processor/download.go:24 +0xd4
github.com/foamzou/audio-get/processor.(*Processor).FetchMetaAndResourceInfo(0xc00019bf68, 0xa995e0, 0x0)
	github.com/foamzou/audio-get/processor/fetch_meta_and_resource_info.go:30 +0x185
github.com/foamzou/audio-get/processor.(*Processor).Process(0xc00019bf68, 0x0, 0x0)
	github.com/foamzou/audio-get/processor/processor.go:15 +0xb5
main.main()
	command-line-arguments/main.go:22 +0x93
```

Cannot download video from the URL, and I try to add `-t audio` tag, the audio download succeed.

**Comment by foamzou** [comment]
Fixed. Can check the latest version

**Comment by Green-m** [comment]
It works, thank you!
